# Generated by Django 2.2.1 on 2019-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emarque', models.CharField(max_length=255)),
                ('adescription', models.CharField(max_length=15)),
                ('aprix', models.CharField(max_length=255)),
                ('acouleur', models.CharField(max_length=255)),
                ('atail', models.CharField(max_length=255)),
                ('aliens', models.TextField()),
                ('acles', models.TextField()),
                ('asource', models.CharField(max_length=255)),
                ('acreated_at', models.DateTimeField(auto_now_add=True)),
                ('aupdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmot', models.TextField()),
                ('rsite', models.CharField(max_length=255)),
                ('rcreated_at', models.DateTimeField(auto_now_add=True)),
                ('rupdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
